# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'DLGPlayerExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
  # use_modular_headers!

  # Pods for DLGPlayerExample
  pod "mobile-ffmpeg-full", "~> 4.2"
  pod 'DLGPlayer', :path => '../'
end
